### PR TITLE
feat(components): rename `x-grid` class to `x-grid-list`

### PR DESCRIPTION
**Pull request by ajperezbau**
BREAKING CHANGE: Rename `x-grid` class to `x-grid-list`.

EX-7481

### CODE REVIEW

**Review by tajespasarela — CHANGES_REQUESTED** [review]
Remember to add breaking changes

**Comment by ajperezbau** [comment]
> Remember to add breaking changes

Shouldn't the breaking change be added to the `squash` commit? 🤔

**Review by LuisMartinez15 — APPROVED** [review]
good job!

**Comment by tajespasarela** [comment]
These classes also changed, include them in breaking changes:
`x-grid-list--cols-`
`x-grid-list__item`

**Review by tajespasarela — APPROVED** [review]

**Pull request merged**
