### PR TITLE
feat(banners): add tagging info banners in platform adapter

### PR DESCRIPTION
**Pull request by diegopf**
EX-7355

### CODE REVIEW

**Review by mnavarroespinosa — COMMENTED** [review]
What would you think of updating the mocked search response (`packages/x-adapter-platform/src/__tests__/__fixtures__/search.response.ts`) with the tagging property? This way we could check that the mapper is working properly.

**Comment by ajperezbau** [comment]
> What would you think of updating the mocked search response (`packages/x-adapter-platform/src/__tests__/__fixtures__/search.response.ts`) with the tagging property for the banners? This way we could check that the mapper is working properly.

Yep, I agree with that, but, do we know where will the API return the tagging for the banners?
I suppose that they will do the same as for the result, and return it in each banner element inside `banner.content`, right?

**Review by ajperezbau — COMMENTED** [review]
Good job 👌

**Review by mnavarroespinosa — APPROVED** [review]
good job!

**Review by ajperezbau — APPROVED** [review]
Good job 👌

**Pull request merged**
