### PR TITLE
ci: migrate from `npm` & `lerna bootstrap` to `pnpm`

### PR DESCRIPTION
**Pull request by LuisMartinez15**
EX-7891

Migrate from `npm` and `lerna bootstrap` to `pnpm` package manager tool.

@empathyco/tech-writers We are migrating the package manager tool from `npm` to `pnpm`, so docs have been updated reflecting this change.

### CODE REVIEW

**Comment by support-empathy** [comment]
This is a link to Empathy Platform Docs Portal preview in a development environment. 
 ⚠️ Only for Empathy members. We’re sorry for the inconvenience!
 [Check out EPDocs preview](https://docs-dev.empathy.co/preview/x-1047/index.html)

**Comment by support-empathy** [comment]
This is a link to Empathy Platform Docs Portal preview in a development environment. 
 ⚠️ Only for Empathy members. We’re sorry for the inconvenience!
 [Check out EPDocs preview](https://docs-dev.empathy.co/preview/x-1047/index.html)

**Comment by support-empathy** [comment]
This is a link to Empathy Platform Docs Portal preview in a development environment. 
 ⚠️ Only for Empathy members. We’re sorry for the inconvenience!
 [Check out EPDocs preview](https://docs-dev.empathy.co/preview/x-1047/index.html)

**Comment by support-empathy** [comment]
This is a link to Empathy Platform Docs Portal preview in a development environment. 
 ⚠️ Only for Empathy members. We’re sorry for the inconvenience!
 [Check out EPDocs preview](https://docs-dev.empathy.co/preview/x-1047/index.html)

**Review by tiborux — APPROVED** [review]

**Review by ajperezbau — DISMISSED** [review]

**Comment by support-empathy** [comment]
This is a link to Empathy Platform Docs Portal preview in a development environment. 
 ⚠️ Only for Empathy members. We’re sorry for the inconvenience!
 [Check out EPDocs preview](https://docs-dev.empathy.co/preview/x-1047/index.html)

**Review by ajperezbau — APPROVED** [review]

**Comment by support-empathy** [comment]
This is a link to Empathy Platform Docs Portal preview in a development environment. 
 ⚠️ Only for Empathy members. We’re sorry for the inconvenience!
 [Check out EPDocs preview](https://docs-dev.empathy.co/preview/x-1047/index.html)

**Review by tiborux — APPROVED** [review]

**Pull request merged**
